from machine import Pin, SPI
import time

# SPI0:
#   SCK  = GP2
#   MOSI = GP3
#   MISO = GP0
#   SS   = GP1
#   RST  = GP14
spi = SPI(
    0,
    baudrate=1_000_000,
    polarity=0,
    phase=0,
    bits=8,
    firstbit=SPI.MSB,
    sck=Pin(2),
    mosi=Pin(3),
    miso=Pin(0),
)

ss = Pin(1, Pin.OUT, value=1)
rst = Pin(14, Pin.OUT, value=1)

CMD_NOP      = 0b00 << 6
CMD_SET_CHAR = 0b01 << 6
CMD_EOL      = 0b10 << 6
CMD_RESET    = 0b11 << 6

NIBBLE_UPPER = 0 << 5
NIBBLE_LOWER = 1 << 5

STATUS_NONE  = 0b00
STATUS_DIGIT = 0b01
STATUS_EOL   = 0b10


def spi_transfer(tx):
    rx = bytearray(1)
    txb = bytearray([tx & 0xff])

    ss.value(0)
    spi.write_readinto(txb, rx)
    ss.value(1)

    return rx[0]


def fpga_reset():
    # FPGA logic reset by command
    spi_transfer(CMD_RESET)
    spi_transfer(CMD_NOP)


def send_char(ch):
    c = ord(ch)

    upper = (c >> 4) & 0x0f
    lower = c & 0x0f

    spi_transfer(CMD_SET_CHAR | NIBBLE_UPPER | upper)
    spi_transfer(CMD_SET_CHAR | NIBBLE_LOWER | lower)

    # Read back result generated by lower nibble RX
    return spi_transfer(CMD_NOP)


def send_eol():
    spi_transfer(CMD_EOL)

    # Read back EOL status
    return spi_transfer(CMD_NOP)


def decode_response(rx):
    status = (rx >> 6) & 0x03
    data = rx & 0x0f

    if status == STATUS_DIGIT:
        return str(data)

    if status == STATUS_EOL:
        return None

    return ""


def run(s):
    fpga_reset()

    ans = ""

    for ch in s:
        rx = send_char(ch)
        decoded = decode_response(rx)

        if decoded is None:
            break

        ans += decoded

    rx = send_eol()
    decode_response(rx)

    return ans


# Test
tests = [
    "abc123def",
    "a1b2c3",
    "hello",
    "0",
    "abc462a",
    "2026-06-14",
]

for s in tests:
    print(s, "=>", run(s))