// ---------------------------------------------------------------------------------
// THIS FILE IS AUTOGENERATED.
//
// IT WILL BE REWRITTEN IN THE NEXT MODEL GENERATION.
// ---------------------------------------------------------------------------------
// Copyright (C) 2025 Renesas Electronics.
// This computer program includes Confidential, Proprietary Information
// of Renesas Electronics. All Rights Reserved.
// ---------------------------------------------------------------------------------
//
// PROJECT NAME         : SLG47910
// VERSION              : 0.1
//
// ---------------------------------------------------------------------------------
//
// NAMING NOTES        :
//                     i_xxxx    -->    represents input signal to the interface
//                     o_xxxx    -->    represents output signal from the interface
//                     w_xxxx    -->    intermediate wire
//                     r_xxxx    -->    internal register
//
//      *As long as this is the hardcoded fpga namings, rules above are not applied
//
// ---------------------------------------------------------------------------------
//
// DESCRIPTION: Wrapper for fpga core (wrapped user's RTL code)
//
// ---------------------------------------------------------------------------------
module fpga_core_abc463c_test (
    input  wire         fpga_core_ready,
    input  wire         func_mode,
    input  wire         nrst,   
    input  wire         nsleep,
    output wire         int_fpga_sleep,
    output wire         int_fpga_reset,
    output wire         ref_logic_as_clk0,
    output wire         ref_logic_as_clk1,
    output wire         logic_as_clk0_en,
    output wire         logic_as_clk1_en,

    input  wire [7:0]   bram0_rdata,
    output wire [7:0]   bram0_wdata,
    output wire [8:0]   bram0_raddr,
    output wire [8:0]   bram0_waddr,
    output wire         bram0_wclkinv,
    output wire         bram0_rclkinv,
    output wire [1:0]   bram0_ratio,
    output wire         bram0_nren,
    output wire         bram0_nrclken,
    output wire         bram0_nwen,
    output wire         bram0_nwclken,

    input  wire [7:0]   bram1_rdata,
    output wire [7:0]   bram1_wdata,
    output wire [8:0]   bram1_raddr,
    output wire [8:0]   bram1_waddr,
    output wire         bram1_wclkinv,
    output wire         bram1_rclkinv,
    output wire [1:0]   bram1_ratio,
    output wire         bram1_nren,
    output wire         bram1_nrclken,
    output wire         bram1_nwen,
    output wire         bram1_nwclken,

    input  wire [7:0]   bram2_rdata,
    output wire [7:0]   bram2_wdata,
    output wire [8:0]   bram2_raddr,
    output wire [8:0]   bram2_waddr,
    output wire         bram2_wclkinv,
    output wire         bram2_rclkinv,
    output wire [1:0]   bram2_ratio,
    output wire         bram2_nren,
    output wire         bram2_nrclken,
    output wire         bram2_nwen,
    output wire         bram2_nwclken,

    input  wire [7:0]   bram3_rdata,
    output wire [7:0]   bram3_wdata,
    output wire [8:0]   bram3_raddr,
    output wire [8:0]   bram3_waddr,
    output wire         bram3_wclkinv,
    output wire         bram3_rclkinv,
    output wire [1:0]   bram3_ratio,
    output wire         bram3_nren,
    output wire         bram3_nrclken,
    output wire         bram3_nwen,
    output wire         bram3_nwclken,

    input  wire [7:0]   bram4_rdata,
    output wire [7:0]   bram4_wdata,
    output wire [8:0]   bram4_raddr,
    output wire [8:0]   bram4_waddr,
    output wire         bram4_wclkinv,
    output wire         bram4_rclkinv,
    output wire [1:0]   bram4_ratio,
    output wire         bram4_nren,
    output wire         bram4_nrclken,
    output wire         bram4_nwen,
    output wire         bram4_nwclken,

    input  wire [7:0]   bram5_rdata,
    output wire [7:0]   bram5_wdata,
    output wire [8:0]   bram5_raddr,
    output wire [8:0]   bram5_waddr,
    output wire         bram5_wclkinv,
    output wire         bram5_rclkinv,
    output wire [1:0]   bram5_ratio,
    output wire         bram5_nren,
    output wire         bram5_nrclken,
    output wire         bram5_nwen,
    output wire         bram5_nwclken,

    input  wire [7:0]   bram6_rdata,
    output wire [7:0]   bram6_wdata,
    output wire [8:0]   bram6_raddr,
    output wire [8:0]   bram6_waddr,
    output wire         bram6_wclkinv,
    output wire         bram6_rclkinv,
    output wire [1:0]   bram6_ratio,
    output wire         bram6_nren,
    output wire         bram6_nrclken,
    output wire         bram6_nwen,
    output wire         bram6_nwclken,

    input  wire [7:0]   bram7_rdata,
    output wire [7:0]   bram7_wdata,
    output wire [8:0]   bram7_raddr,
    output wire [8:0]   bram7_waddr,
    output wire         bram7_wclkinv,
    output wire         bram7_rclkinv,
    output wire [1:0]   bram7_ratio,
    output wire         bram7_nren,
    output wire         bram7_nrclken,
    output wire         bram7_nwen,
    output wire         bram7_nwclken,

    input  wire         logic_as_clk0,
    input  wire         logic_as_clk1,
    input  wire         osc_clk,
    input  wire         pll_clk,
    output wire         ref_bram_0_3_read_clk,
    output wire         ref_bram_0_3_write_clk,
    output wire         ref_bram_4_7_read_clk,
    output wire         ref_bram_4_7_write_clk,

    input  wire [18:0]  gpio_in,
    output wire [18:0]  gpio_oe,
    output wire [18:0]  gpio_out,

    input  wire         osc_ready,
    output wire         osc_en,

    input  wire         pll_lock,
    output wire         pll_ref_clk_sel,
    output wire         pll_bypass,
    output wire         pll_en,
    output wire [11:0]  pll_fbdiv,
    output wire [2:0]   pll_postdiv1,
    output wire [2:0]   pll_postdiv2,
    output wire [5:0]   pll_refdiv
);

    // Intermediate wires for delayed connections
    wire gpio_out_6_to_delay;

    assign #3.6 gpio_out[6] = gpio_out_6_to_delay;

    top dut (
        .spi_miso_en(gpio_oe[6]),
        .clk_en(osc_en),
        .clk(osc_clk),
        .spi_ss_n(gpio_in[4]),
        .spi_mosi(gpio_in[5]),
        .spi_sck(gpio_in[3]),
        .rst_n(gpio_in[18]),
        .spi_miso(gpio_out_6_to_delay)
    );


    assign ref_bram_0_3_read_clk = 1'b0;
    assign ref_bram_0_3_write_clk = 1'b0;
    assign ref_bram_4_7_read_clk = 1'b0;
    assign ref_bram_4_7_write_clk = 1'b0;
    assign bram4_wdata[5] = 1'b0;
    assign bram4_wdata[4] = 1'b0;
    assign gpio_out[4] = 1'b0;
    assign gpio_oe[4] = 1'b0;
    assign pll_ref_clk_sel = 1'b0;
    assign pll_bypass = 1'b0;
    assign pll_fbdiv[0] = 1'b0;
    assign pll_fbdiv[1] = 1'b0;
    assign pll_fbdiv[2] = 1'b0;
    assign pll_fbdiv[3] = 1'b0;
    assign pll_fbdiv[4] = 1'b0;
    assign pll_fbdiv[5] = 1'b0;
    assign pll_fbdiv[6] = 1'b0;
    assign pll_fbdiv[7] = 1'b0;
    assign pll_fbdiv[8] = 1'b0;
    assign pll_fbdiv[9] = 1'b0;
    assign pll_fbdiv[10] = 1'b0;
    assign pll_fbdiv[11] = 1'b0;
    assign pll_en = 1'b0;
    assign int_fpga_sleep = 1'b0;
    assign pll_postdiv1[0] = 1'b0;
    assign pll_postdiv1[1] = 1'b0;
    assign bram4_wdata[7] = 1'b0;
    assign bram4_wdata[6] = 1'b0;
    assign pll_postdiv1[2] = 1'b0;
    assign pll_postdiv2[0] = 1'b0;
    assign pll_postdiv2[1] = 1'b0;
    assign pll_postdiv2[2] = 1'b0;
    assign gpio_out[5] = 1'b0;
    assign gpio_oe[5] = 1'b0;
    assign gpio_out[7] = 1'b0;
    assign gpio_oe[7] = 1'b0;
    assign bram0_nwen = 1'b0;
    assign bram0_nwclken = 1'b0;
    assign bram0_nren = 1'b0;
    assign bram0_nrclken = 1'b0;
    assign bram0_ratio[0] = 1'b0;
    assign bram0_ratio[1] = 1'b0;
    assign bram0_wclkinv = 1'b0;
    assign bram0_rclkinv = 1'b0;
    assign bram4_wclkinv = 1'b0;
    assign bram4_rclkinv = 1'b0;
    assign bram0_wdata[7] = 1'b0;
    assign bram0_wdata[6] = 1'b0;
    assign bram0_wdata[5] = 1'b0;
    assign bram0_wdata[4] = 1'b0;
    assign bram4_ratio[0] = 1'b0;
    assign bram4_ratio[1] = 1'b0;
    assign bram4_nren = 1'b0;
    assign bram4_nrclken = 1'b0;
    assign bram4_nwen = 1'b0;
    assign bram4_nwclken = 1'b0;
    assign gpio_out[0] = 1'b0;
    assign gpio_oe[0] = 1'b0;
    assign gpio_out[1] = 1'b0;
    assign gpio_oe[1] = 1'b0;
    assign gpio_out[2] = 1'b0;
    assign gpio_oe[2] = 1'b0;
    assign gpio_out[3] = 1'b0;
    assign gpio_oe[3] = 1'b0;
    assign bram5_wdata[1] = 1'b0;
    assign bram5_wdata[0] = 1'b0;
    assign bram5_wdata[3] = 1'b0;
    assign bram5_wdata[2] = 1'b0;
    assign bram1_wdata[3] = 1'b0;
    assign bram1_wdata[2] = 1'b0;
    assign bram1_wdata[1] = 1'b0;
    assign bram1_wdata[0] = 1'b0;
    assign bram5_waddr[6] = 1'b0;
    assign bram5_waddr[5] = 1'b0;
    assign bram5_waddr[8] = 1'b0;
    assign bram5_waddr[7] = 1'b0;
    assign bram1_waddr[8] = 1'b0;
    assign bram1_waddr[7] = 1'b0;
    assign bram1_waddr[6] = 1'b0;
    assign bram1_waddr[5] = 1'b0;
    assign bram5_waddr[2] = 1'b0;
    assign bram5_waddr[1] = 1'b0;
    assign bram5_waddr[4] = 1'b0;
    assign bram5_waddr[3] = 1'b0;
    assign bram1_waddr[4] = 1'b0;
    assign bram1_waddr[3] = 1'b0;
    assign bram1_waddr[2] = 1'b0;
    assign bram1_waddr[1] = 1'b0;
    assign bram5_raddr[7] = 1'b0;
    assign bram5_raddr[6] = 1'b0;
    assign bram5_waddr[0] = 1'b0;
    assign bram5_raddr[8] = 1'b0;
    assign bram1_waddr[0] = 1'b0;
    assign bram1_raddr[8] = 1'b0;
    assign bram1_raddr[7] = 1'b0;
    assign bram1_raddr[6] = 1'b0;
    assign bram5_raddr[3] = 1'b0;
    assign bram5_raddr[2] = 1'b0;
    assign bram5_raddr[5] = 1'b0;
    assign bram5_raddr[4] = 1'b0;
    assign bram1_raddr[5] = 1'b0;
    assign bram1_raddr[4] = 1'b0;
    assign bram1_raddr[3] = 1'b0;
    assign bram1_raddr[2] = 1'b0;
    assign bram6_nwen = 1'b0;
    assign bram6_nwclken = 1'b0;
    assign bram5_raddr[1] = 1'b0;
    assign bram5_raddr[0] = 1'b0;
    assign bram1_raddr[1] = 1'b0;
    assign bram1_raddr[0] = 1'b0;
    assign bram2_nwen = 1'b0;
    assign bram2_nwclken = 1'b0;
    assign bram6_ratio[1] = 1'b0;
    assign bram6_ratio[0] = 1'b0;
    assign bram6_nren = 1'b0;
    assign bram6_nrclken = 1'b0;
    assign bram2_nren = 1'b0;
    assign bram2_nrclken = 1'b0;
    assign bram2_ratio[1] = 1'b0;
    assign bram2_ratio[0] = 1'b0;
    assign bram6_wdata[7] = 1'b0;
    assign bram6_wdata[6] = 1'b0;
    assign bram6_wclkinv = 1'b0;
    assign bram6_rclkinv = 1'b0;
    assign bram2_wclkinv = 1'b0;
    assign bram2_rclkinv = 1'b0;
    assign bram2_wdata[7] = 1'b0;
    assign bram2_wdata[6] = 1'b0;
    assign bram6_wdata[3] = 1'b0;
    assign bram6_wdata[2] = 1'b0;
    assign bram6_wdata[5] = 1'b0;
    assign bram6_wdata[4] = 1'b0;
    assign bram2_wdata[5] = 1'b0;
    assign bram2_wdata[4] = 1'b0;
    assign bram2_wdata[3] = 1'b0;
    assign bram2_wdata[2] = 1'b0;
    assign bram6_waddr[8] = 1'b0;
    assign bram6_waddr[7] = 1'b0;
    assign bram6_wdata[1] = 1'b0;
    assign bram6_wdata[0] = 1'b0;
    assign bram2_wdata[1] = 1'b0;
    assign bram2_wdata[0] = 1'b0;
    assign bram2_waddr[8] = 1'b0;
    assign bram2_waddr[7] = 1'b0;
    assign bram4_wdata[1] = 1'b0;
    assign bram4_wdata[0] = 1'b0;
    assign bram4_wdata[3] = 1'b0;
    assign bram4_wdata[2] = 1'b0;
    assign bram0_wdata[3] = 1'b0;
    assign bram0_wdata[2] = 1'b0;
    assign bram0_wdata[1] = 1'b0;
    assign bram0_wdata[0] = 1'b0;
    assign bram6_waddr[4] = 1'b0;
    assign bram6_waddr[3] = 1'b0;
    assign bram6_waddr[6] = 1'b0;
    assign bram6_waddr[5] = 1'b0;
    assign bram2_waddr[6] = 1'b0;
    assign bram2_waddr[5] = 1'b0;
    assign bram2_waddr[4] = 1'b0;
    assign bram2_waddr[3] = 1'b0;
    assign bram6_waddr[0] = 1'b0;
    assign bram6_raddr[8] = 1'b0;
    assign bram6_waddr[2] = 1'b0;
    assign bram6_waddr[1] = 1'b0;
    assign bram2_waddr[2] = 1'b0;
    assign bram2_waddr[1] = 1'b0;
    assign bram2_waddr[0] = 1'b0;
    assign bram2_raddr[8] = 1'b0;
    assign bram6_raddr[5] = 1'b0;
    assign bram6_raddr[4] = 1'b0;
    assign bram6_raddr[7] = 1'b0;
    assign bram6_raddr[6] = 1'b0;
    assign bram2_raddr[7] = 1'b0;
    assign bram2_raddr[6] = 1'b0;
    assign bram2_raddr[5] = 1'b0;
    assign bram2_raddr[4] = 1'b0;
    assign bram6_raddr[1] = 1'b0;
    assign bram6_raddr[0] = 1'b0;
    assign bram6_raddr[3] = 1'b0;
    assign bram6_raddr[2] = 1'b0;
    assign bram2_raddr[3] = 1'b0;
    assign bram2_raddr[2] = 1'b0;
    assign bram2_raddr[1] = 1'b0;
    assign bram2_raddr[0] = 1'b0;
    assign bram7_nwen = 1'b0;
    assign bram7_nwclken = 1'b0;
    assign bram3_nwen = 1'b0;
    assign bram3_nwclken = 1'b0;
    assign bram7_ratio[1] = 1'b0;
    assign bram7_ratio[0] = 1'b0;
    assign bram7_nren = 1'b0;
    assign bram7_nrclken = 1'b0;
    assign bram3_nren = 1'b0;
    assign bram3_nrclken = 1'b0;
    assign bram3_ratio[1] = 1'b0;
    assign bram3_ratio[0] = 1'b0;
    assign bram7_wdata[7] = 1'b0;
    assign bram7_wdata[6] = 1'b0;
    assign bram7_wclkinv = 1'b0;
    assign bram7_rclkinv = 1'b0;
    assign bram3_wclkinv = 1'b0;
    assign bram3_rclkinv = 1'b0;
    assign bram3_wdata[7] = 1'b0;
    assign bram3_wdata[6] = 1'b0;
    assign bram7_wdata[3] = 1'b0;
    assign bram7_wdata[2] = 1'b0;
    assign bram7_wdata[5] = 1'b0;
    assign bram7_wdata[4] = 1'b0;
    assign bram3_wdata[5] = 1'b0;
    assign bram3_wdata[4] = 1'b0;
    assign bram3_wdata[3] = 1'b0;
    assign bram3_wdata[2] = 1'b0;
    assign bram7_waddr[8] = 1'b0;
    assign bram7_waddr[7] = 1'b0;
    assign bram7_wdata[1] = 1'b0;
    assign bram7_wdata[0] = 1'b0;
    assign bram3_wdata[1] = 1'b0;
    assign bram3_wdata[0] = 1'b0;
    assign bram3_waddr[8] = 1'b0;
    assign bram3_waddr[7] = 1'b0;
    assign bram7_waddr[4] = 1'b0;
    assign bram7_waddr[3] = 1'b0;
    assign bram7_waddr[6] = 1'b0;
    assign bram7_waddr[5] = 1'b0;
    assign bram3_waddr[6] = 1'b0;
    assign bram3_waddr[5] = 1'b0;
    assign bram3_waddr[4] = 1'b0;
    assign bram3_waddr[3] = 1'b0;
    assign bram4_waddr[6] = 1'b0;
    assign bram4_waddr[5] = 1'b0;
    assign bram4_waddr[8] = 1'b0;
    assign bram4_waddr[7] = 1'b0;
    assign bram0_waddr[8] = 1'b0;
    assign bram0_waddr[7] = 1'b0;
    assign bram0_waddr[6] = 1'b0;
    assign bram0_waddr[5] = 1'b0;
    assign bram7_waddr[0] = 1'b0;
    assign bram7_raddr[8] = 1'b0;
    assign bram7_waddr[2] = 1'b0;
    assign bram7_waddr[1] = 1'b0;
    assign bram3_waddr[2] = 1'b0;
    assign bram3_waddr[1] = 1'b0;
    assign bram3_waddr[0] = 1'b0;
    assign bram3_raddr[8] = 1'b0;
    assign bram7_raddr[5] = 1'b0;
    assign bram7_raddr[4] = 1'b0;
    assign int_fpga_reset = 1'b0;
    assign ref_logic_as_clk0 = 1'b0;
    assign ref_logic_as_clk1 = 1'b0;
    assign logic_as_clk0_en = 1'b0;
    assign logic_as_clk1_en = 1'b0;
    assign pll_refdiv[0] = 1'b0;
    assign pll_refdiv[1] = 1'b0;
    assign bram7_raddr[7] = 1'b0;
    assign bram7_raddr[6] = 1'b0;
    assign pll_refdiv[2] = 1'b0;
    assign pll_refdiv[3] = 1'b0;
    assign pll_refdiv[4] = 1'b0;
    assign pll_refdiv[5] = 1'b0;
    assign gpio_out[13] = 1'b0;
    assign gpio_oe[13] = 1'b0;
    assign gpio_out[12] = 1'b0;
    assign gpio_oe[12] = 1'b0;
    assign gpio_out[11] = 1'b0;
    assign gpio_oe[11] = 1'b0;
    assign gpio_out[10] = 1'b0;
    assign gpio_oe[10] = 1'b0;
    assign gpio_out[9] = 1'b0;
    assign gpio_oe[9] = 1'b0;
    assign gpio_out[8] = 1'b0;
    assign gpio_oe[8] = 1'b0;
    assign bram3_raddr[1] = 1'b0;
    assign bram3_raddr[0] = 1'b0;
    assign bram3_raddr[3] = 1'b0;
    assign bram3_raddr[2] = 1'b0;
    assign bram7_raddr[3] = 1'b0;
    assign bram7_raddr[2] = 1'b0;
    assign bram3_raddr[7] = 1'b0;
    assign bram3_raddr[6] = 1'b0;
    assign bram3_raddr[5] = 1'b0;
    assign bram3_raddr[4] = 1'b0;
    assign bram7_raddr[1] = 1'b0;
    assign bram7_raddr[0] = 1'b0;
    assign gpio_out[18] = 1'b0;
    assign gpio_oe[18] = 1'b0;
    assign gpio_out[17] = 1'b0;
    assign gpio_oe[17] = 1'b0;
    assign gpio_out[16] = 1'b0;
    assign gpio_oe[16] = 1'b0;
    assign gpio_out[15] = 1'b0;
    assign gpio_oe[15] = 1'b0;
    assign gpio_out[14] = 1'b0;
    assign gpio_oe[14] = 1'b0;
    assign bram4_waddr[2] = 1'b0;
    assign bram4_waddr[1] = 1'b0;
    assign bram4_waddr[4] = 1'b0;
    assign bram4_waddr[3] = 1'b0;
    assign bram0_waddr[4] = 1'b0;
    assign bram0_waddr[3] = 1'b0;
    assign bram0_waddr[2] = 1'b0;
    assign bram0_waddr[1] = 1'b0;
    assign bram4_raddr[7] = 1'b0;
    assign bram4_raddr[6] = 1'b0;
    assign bram4_waddr[0] = 1'b0;
    assign bram4_raddr[8] = 1'b0;
    assign bram0_waddr[0] = 1'b0;
    assign bram0_raddr[8] = 1'b0;
    assign bram0_raddr[7] = 1'b0;
    assign bram0_raddr[6] = 1'b0;
    assign bram4_raddr[3] = 1'b0;
    assign bram4_raddr[2] = 1'b0;
    assign bram4_raddr[5] = 1'b0;
    assign bram4_raddr[4] = 1'b0;
    assign bram0_raddr[5] = 1'b0;
    assign bram0_raddr[4] = 1'b0;
    assign bram0_raddr[3] = 1'b0;
    assign bram0_raddr[2] = 1'b0;
    assign bram4_raddr[1] = 1'b0;
    assign bram4_raddr[0] = 1'b0;
    assign bram0_raddr[1] = 1'b0;
    assign bram0_raddr[0] = 1'b0;
    assign bram5_nren = 1'b0;
    assign bram5_nrclken = 1'b0;
    assign bram5_nwen = 1'b0;
    assign bram5_nwclken = 1'b0;
    assign bram1_nwen = 1'b0;
    assign bram1_nwclken = 1'b0;
    assign bram1_nren = 1'b0;
    assign bram1_nrclken = 1'b0;
    assign bram5_wclkinv = 1'b0;
    assign bram5_rclkinv = 1'b0;
    assign bram5_ratio[1] = 1'b0;
    assign bram5_ratio[0] = 1'b0;
    assign bram1_ratio[1] = 1'b0;
    assign bram1_ratio[0] = 1'b0;
    assign bram1_wclkinv = 1'b0;
    assign bram1_rclkinv = 1'b0;
    assign bram5_wdata[5] = 1'b0;
    assign bram5_wdata[4] = 1'b0;
    assign bram5_wdata[7] = 1'b0;
    assign bram5_wdata[6] = 1'b0;
    assign bram1_wdata[7] = 1'b0;
    assign bram1_wdata[6] = 1'b0;
    assign bram1_wdata[5] = 1'b0;
    assign bram1_wdata[4] = 1'b0;


endmodule