// ---------------------------------------------------------------------------------
// THIS FILE IS AUTOGENERATED.
//
// IT WILL BE REWRITTEN IN THE NEXT MODEL GENERATION.
// ---------------------------------------------------------------------------------
// Copyright (C) 2025 Renesas Electronics.
// This computer program includes Confidential, Proprietary Information
// of Renesas Electronics. All Rights Reserved.
// ---------------------------------------------------------------------------------
//
// PROJECT NAME         : slg47910V
// VERSION              : 0.1
//
// ---------------------------------------------------------------------------------
//
// NAMING NOTES        :
//                     i_xxxx    -->    represents input signal to the interface
//                     o_xxxx    -->    represents output signal from the interface
//                     w_xxxx    -->    intermediate wire
//                     r_xxxx    -->    internal register
//
// ---------------------------------------------------------------------------------
//
// DESCRIPTION: Wrapper for QFN24 SLG47910V device
//
// ---------------------------------------------------------------------------------
`timescale 1ns/1ps

//`include "model_lib/modellib.v"
module SLG47910V_abc463c_test (
    inout wire io_gpio10    ,  //   p1
    inout wire io_gpio11    ,  //   p2
    inout wire io_gpio12    ,  //   p3
    inout wire io_gpio13    ,  //   p4
    inout wire io_gpio14    ,  //   p5
    inout wire io_gpio15    ,  //   p6
    inout wire io_gpio16    ,  //   p7
    inout wire io_gpio17    ,  //   p8
    inout wire io_gpio18    ,  //   p9
    inout wire i_nsleep     ,  //   p10
    inout wire i_nrst       ,  //   p11
    input wire i_vss        ,  //   p12
    inout wire io_gpio0     ,  //   p13
    inout wire io_gpio1     ,  //   p14
    inout wire io_gpio2     ,  //   p15
    inout wire io_gpio3     ,  //   p16
    inout wire io_gpio4     ,  //   p17
    inout wire io_gpio5     ,  //   p18
    inout wire io_gpio6     ,  //   p19
    inout wire io_gpio7     ,  //   p20
    input wire i_vddio      ,  //   p21
    input wire i_vddc       ,  //   p22
    inout wire io_gpio8     ,  //   p23
    inout wire io_gpio9        //   p24
);
    wire w_poc;
    assign w_poc = i_vddc && ~i_vss && i_vddio ;
//----------------------------------------------------------------------------------//
//                                       nRST                                       //
//----------------------------------------------------------------------------------//
    wire w_nrst_din;
    assign w_nrst_din = w_poc ? i_nrst : 1'bx;

    wire w_nrst_pullup_en;
    assign w_nrst_pullup_en = r_otp_reg[9][16] || w_nSLEEP_nRST_pullup_en || w_nrst_din;
    assign (pull1, highz0) i_nrst = w_nrst_pullup_en && w_poc ? 1'b1 : 1'bz;
//----------------------------------------------------------------------------------//
//                                     nSLEEP                                       //
//----------------------------------------------------------------------------------//
    wire w_nsleep_din;
    assign w_nsleep_din = w_poc ? i_nsleep : 1'bx;

    wire w_nsleep_pullup_en;
    assign w_nsleep_pullup_en = r_otp_reg[9][17] || w_nSLEEP_nRST_pullup_en || w_nsleep_din;
    assign (pull1, highz0) i_nsleep = w_nsleep_pullup_en && w_poc ? 1'b1 : 1'bz;

//----------------------------------------------------------------------------------//
//                                     GPIO                                         //
//----------------------------------------------------------------------------------//
    wire [18:0]  w_1x_pullup_en_pad_ctrl_to_gpio   ;
    wire [18:0]  w_2x_pullup_en_pad_ctrl_to_gpio   ;
    wire [18:0]  w_digital_input_gpio_to_pad_ctrl  ;
    wire [18:0]  w_open_drain_en_pad_ctrl_to_gpio  ;
    wire [18:0]  w_2x_buffer_en_pad_ctrl_to_gpio   ;
    wire [18:0]  w_digital_out_en_pad_ctrl_to_gpio ;
    wire [18:0]  w_digital_output_pad_ctrl_to_gpio ;   
    wire [18:0]  w_io_gpio_bus                     ;   

    tran t_io_gpio18 (io_gpio18, w_io_gpio_bus[18]);
    tran t_io_gpio17 (io_gpio17, w_io_gpio_bus[17]);
    tran t_io_gpio16 (io_gpio16, w_io_gpio_bus[16]);
    tran t_io_gpio15 (io_gpio15, w_io_gpio_bus[15]);
    tran t_io_gpio14 (io_gpio14, w_io_gpio_bus[14]);
    tran t_io_gpio13 (io_gpio13, w_io_gpio_bus[13]);
    tran t_io_gpio12 (io_gpio12, w_io_gpio_bus[12]);
    tran t_io_gpio11 (io_gpio11, w_io_gpio_bus[11]);
    tran t_io_gpio10 (io_gpio10, w_io_gpio_bus[10]);
    tran t_io_gpio9  (io_gpio9 , w_io_gpio_bus[9 ]);
    tran t_io_gpio8  (io_gpio8 , w_io_gpio_bus[8 ]);
    tran t_io_gpio7  (io_gpio7 , w_io_gpio_bus[7 ]);
    tran t_io_gpio6  (io_gpio6 , w_io_gpio_bus[6 ]);
    tran t_io_gpio5  (io_gpio5 , w_io_gpio_bus[5 ]);
    tran t_io_gpio4  (io_gpio4 , w_io_gpio_bus[4 ]);
    tran t_io_gpio3  (io_gpio3 , w_io_gpio_bus[3 ]);
    tran t_io_gpio2  (io_gpio2 , w_io_gpio_bus[2 ]);
    tran t_io_gpio1  (io_gpio1 , w_io_gpio_bus[1 ]);
    tran t_io_gpio0  (io_gpio0 , w_io_gpio_bus[0 ]);

    genvar gpio_idx;
    generate
        for (gpio_idx = 0; gpio_idx < 19; gpio_idx = gpio_idx + 1) begin : gpio_inst
            gpio u_gpio(
                .i_vddc           	(i_vddc                                         ),
                .i_vddio          	(i_vddio                                        ),
                .i_1x_pullup_en   	(w_1x_pullup_en_pad_ctrl_to_gpio  [gpio_idx]    ),
                .i_2x_pullup_en   	(w_2x_pullup_en_pad_ctrl_to_gpio  [gpio_idx]    ),
                .o_digital_input  	(w_digital_input_gpio_to_pad_ctrl [gpio_idx]    ),
                .i_open_drain_en  	(w_open_drain_en_pad_ctrl_to_gpio [gpio_idx]    ),
                .i_2x_buffer_en   	(w_2x_buffer_en_pad_ctrl_to_gpio  [gpio_idx]    ),
                .i_digital_out_en 	(w_digital_out_en_pad_ctrl_to_gpio_dly[gpio_idx]),
                .i_digital_output 	(w_digital_output_pad_ctrl_to_gpio_dly[gpio_idx]),
                .pad              	(w_io_gpio_bus[gpio_idx]                        )
            );
        end
    endgenerate

    wire w_por;
//----------------------------------------------------------------------------------//
//                                  PAD CONTROLLER                                  //
//----------------------------------------------------------------------------------//
    wire [18:0] w_gpio_digital_in_pad_ctrl_to_iob;
    wire [18:0] w_iob_digital_out_to_pad_ctrl;
    wire [18:0] w_iob_output_enable_to_pad_ctrl;
    pad_ctrl #(
        .GPIO_NUMB 	(19))
    u_pad_ctrl(
        .i_rst_n                       	(w_por                                  ),
        .i_clk                         	(w_ctrl_clk                             ),
        .i_retention_cfg_reg_set       	(w_retention_cfg_reg_set                ),
        .i_retention_iob_set           	(w_retention_iob_set                    ),
        .i_retention_cfg_reg_rst       	(w_retention_cfg_reg_rst                ),
        .i_retention_iob_rst           	(w_retention_iob_rst                    ),
        .i_ctrl_gpio_fn_inp_gating     	(w_ctrl_gpio_fn_inp_gating              ),
        .i_ctrl_gpio_fn_out_gating     	(w_ctrl_gpio_fn_out_gating              ),
        .i_ctrl_gpio_fn_oe_gating      	(w_ctrl_gpio_fn_oe_gating               ),
        .i_gpio_digital_in             	(w_digital_input_gpio_to_pad_ctrl_dly   ),
        .i_iob_digital_out             	(w_iob_digital_out_to_pad_ctrl_dly      ),
        .i_iob_output_enable           	(w_iob_output_enable_to_pad_ctrl_dly    ),
        .i_ctrl_gpio_1x_pullup_en_reg  	(w_ctrl_gpio_1x_pullup_en_reg           ),
        .i_1x_pullup_en_reg_val        	(w_1x_pullup_en_reg_val                 ),
        .i_1x_pullup_en_def_val        	(r_1x_pullup_en_def_val                 ),
        .i_ctrl_gpio_2x_pullup_en_reg  	(w_ctrl_gpio_2x_pullup_en_reg           ),
        .i_2x_pullup_en_reg_val        	(w_2x_pullup_en_reg_val                 ),
        .i_2x_pullup_en_def_val        	(r_2x_pullup_en_def_val                 ),
        .i_ctrl_gpio_2x_buffer_en_reg  	(w_ctrl_gpio_2x_buffer_en_reg           ),
        .i_2x_buffer_en_reg_val        	(w_2x_buffer_en_reg_val                 ),
        .i_2x_buffer_en_def_val        	(r_2x_buffer_en_def_val                 ),
        .i_ctrl_gpio_open_drain_en_reg 	(w_ctrl_gpio_open_drain_en_reg          ),
        .i_open_drain_en_reg_val       	(w_open_drain_en_reg_val                ),
        .i_open_drain_en_def_val       	(r_open_drain_en_def_val                ),
        .o_gpio_digital_in             	(w_gpio_digital_in_pad_ctrl_to_iob      ),
        .o_1x_pullup_en_q              	(w_1x_pullup_en_pad_ctrl_to_gpio        ),
        .o_2x_pullup_en_q              	(w_2x_pullup_en_pad_ctrl_to_gpio        ),
        .o_2x_buffer_en_q              	(w_2x_buffer_en_pad_ctrl_to_gpio        ),
        .o_open_drain_en_q             	(w_open_drain_en_pad_ctrl_to_gpio       ),
        .o_digital_out_en_q            	(w_digital_out_en_pad_ctrl_to_gpio      ),
        .o_digital_output_q            	(w_digital_output_pad_ctrl_to_gpio      )
    );

    reg [18:0] r_1x_pullup_en_def_val  = 19'h00000;
    reg [18:0] r_2x_pullup_en_def_val  = 19'h00000;
    reg [18:0] r_2x_buffer_en_def_val  = 19'h00000;
    reg [18:0] r_open_drain_en_def_val = 19'h00000;

    wire [18:0] w_1x_pullup_en_reg_val;
    assign w_1x_pullup_en_reg_val = {r_otp_reg [9] [9],
                                     r_otp_reg [9] [5],
                                     r_otp_reg [9] [1],
                                     r_otp_reg [8] [29],
                                     r_otp_reg [8] [25],
                                     r_otp_reg [8] [21],
                                     r_otp_reg [8] [17],
                                     r_otp_reg [8] [13],
                                     r_otp_reg [8] [9],
                                     r_otp_reg [8] [5],
                                     r_otp_reg [8] [1],
                                     r_otp_reg [7] [29],
                                     r_otp_reg [7] [25],
                                     r_otp_reg [7] [21],
                                     r_otp_reg [7] [17],
                                     r_otp_reg [7] [13],
                                     r_otp_reg [7] [9],
                                     r_otp_reg [7] [5],
                                     r_otp_reg [7] [1]
                                     };

    wire [18:0] w_2x_pullup_en_reg_val;
    assign w_2x_pullup_en_reg_val = {r_otp_reg [9] [8],
                                     r_otp_reg [9] [4],
                                     r_otp_reg [9] [0],
                                     r_otp_reg [8] [28],
                                     r_otp_reg [8] [24],
                                     r_otp_reg [8] [20],
                                     r_otp_reg [8] [16],
                                     r_otp_reg [8] [12],
                                     r_otp_reg [8] [8],
                                     r_otp_reg [8] [4],
                                     r_otp_reg [8] [0],
                                     r_otp_reg [7] [28],
                                     r_otp_reg [7] [24],
                                     r_otp_reg [7] [20],
                                     r_otp_reg [7] [16],
                                     r_otp_reg [7] [12],
                                     r_otp_reg [7] [8],
                                     r_otp_reg [7] [4],
                                     r_otp_reg [7] [0]
                                     };

    wire [18:0] w_open_drain_en_reg_val;
    assign w_open_drain_en_reg_val = {r_otp_reg [9] [10],
                                      r_otp_reg [9] [6],
                                      r_otp_reg [9] [2],
                                      r_otp_reg [8] [30],
                                      r_otp_reg [8] [26],
                                      r_otp_reg [8] [22],
                                      r_otp_reg [8] [18],
                                      r_otp_reg [8] [14],
                                      r_otp_reg [8] [10],
                                      r_otp_reg [8] [6],
                                      r_otp_reg [8] [2],
                                      r_otp_reg [7] [30],
                                      r_otp_reg [7] [26],
                                      r_otp_reg [7] [22],
                                      r_otp_reg [7] [18],
                                      r_otp_reg [7] [14],
                                      r_otp_reg [7] [10],
                                      r_otp_reg [7] [6],
                                      r_otp_reg [7] [2]
                                      };

    wire [18:0] w_2x_buffer_en_reg_val;
    assign w_2x_buffer_en_reg_val  = {r_otp_reg [9] [11],
                                      r_otp_reg [9] [7],
                                      r_otp_reg [9] [3],
                                      r_otp_reg [8] [31],
                                      r_otp_reg [8] [27],
                                      r_otp_reg [8] [23],
                                      r_otp_reg [8] [19],
                                      r_otp_reg [8] [15],
                                      r_otp_reg [8] [11],
                                      r_otp_reg [8] [7],
                                      r_otp_reg [8] [3],
                                      r_otp_reg [7] [31],
                                      r_otp_reg [7] [27],
                                      r_otp_reg [7] [23],
                                      r_otp_reg [7] [19],
                                      r_otp_reg [7] [15],
                                      r_otp_reg [7] [11],
                                      r_otp_reg [7] [7],
                                      r_otp_reg [7] [3]
                                      };
//----------------------------------------------------------------------------------//
//                                POWER CONTROLLER                                  //
//----------------------------------------------------------------------------------//
    wire w_vdd_ok;
    assign w_vdd_ok = i_vddc && ~i_vss && i_vddio;
    assign #(1.5e6, 10) w_por = i_vddc && ~i_vss && i_vddio ;

//----------------------------------------------------------------------------------//
//                                       OTP                                        //
//----------------------------------------------------------------------------------//
    reg [31:0] r_otp_reg[0:14];

    integer reg_idx;
    /* OTP_BEGIN */
    parameter [31:0] OTPDATA0  = 32'h2800_0000;
    parameter [31:0] OTPDATA1  = 32'h0000_0000;
    parameter [31:0] OTPDATA2  = 32'hA5A5_A5A5;
    parameter [31:0] OTPDATA3  = 32'h0000_0000;
    parameter [31:0] OTPDATA4  = 32'h0000_0000;
    parameter [31:0] OTPDATA5  = 32'h5A5A_5A5A;
    parameter [31:0] OTPDATA6  = 32'h0000_0000;
    parameter [31:0] OTPDATA7  = 32'h2222_2222;
    parameter [31:0] OTPDATA8  = 32'h2222_2222;
    parameter [31:0] OTPDATA9  = 32'h0000_2222;
    parameter [31:0] OTPDATA10 = 32'h0000_0003;
    parameter [31:0] OTPDATA11 = 32'h0000_0000;
    parameter [31:0] OTPDATA12 = 32'h0000_0000;
    parameter [31:0] OTPDATA13 = 32'h0000_0000;
    parameter [31:0] OTPDATA14 = 32'h0000_0000;
    /* OTP_END */

    always @(*) begin
        if(!w_por) begin 
            for (reg_idx = 0; reg_idx < 15; reg_idx = reg_idx + 1) begin 
                r_otp_reg [reg_idx] = 0;
            end
        end
        else if(w_ctrl_current_state == `S_LOAD_BITSTREAM) begin
            r_otp_reg [0]  = OTPDATA0;
            r_otp_reg [1]  = OTPDATA1;
            r_otp_reg [2]  = OTPDATA2;
            r_otp_reg [3]  = OTPDATA3;
            r_otp_reg [4]  = OTPDATA4;
            r_otp_reg [5]  = OTPDATA5;
            r_otp_reg [6]  = OTPDATA6;
            r_otp_reg [7]  = OTPDATA7;
            r_otp_reg [8]  = OTPDATA8;
            r_otp_reg [9]  = OTPDATA9;
            r_otp_reg [10] = OTPDATA10;
            r_otp_reg [11] = OTPDATA11;
            r_otp_reg [12] = OTPDATA12;
            r_otp_reg [13] = OTPDATA13;
            r_otp_reg [14] = OTPDATA14;
        end
    end
//----------------------------------------------------------------------------------//
//                                    MAIN FSM                                      //
//----------------------------------------------------------------------------------//
    wire w_nSLEEP_nRST_pullup_en;
    wire w_ctrl_clk;
    wire w_ctrl_clk_rdy;
    wire w_user_clk_ready;
    wire w_all_user_clk_low;

    wire w_iob_osc_en;
    wire w_osc_ready_user;
    wire w_osc_ready_block;
    wire w_iob_pll_en;
    wire w_pll_rdy;

    wire w_iob_func_mode;
    wire w_int_rst;
    wire w_sleep_start;
    wire w_force_dev_sleep_dis;
    wire w_gpio_keep;

    wire w_retention_cfg_reg_set;
    wire w_retention_iob_set;
    wire w_retention_cfg_reg_rst;
    wire w_retention_iob_rst;
    wire w_ctrl_gpio_fn_inp_gating;
    wire w_ctrl_gpio_fn_out_gating;
    wire w_ctrl_gpio_fn_oe_gating;
    wire w_ctrl_gpio_1x_pullup_en_reg;
    wire w_ctrl_gpio_2x_pullup_en_reg;
    wire w_ctrl_gpio_2x_buffer_en_reg;
    wire w_ctrl_gpio_open_drain_en_reg;

    wire w_ctrl_clk_req;
    wire w_pll_override;
    wire w_osc_en_override;
    wire w_all_user_clk_rst;

    wire w_nRST_iso_en;
    wire w_bram_sleep_en;
    wire w_bram_rst_en;
    wire w_config_done;
    wire w_pll_ready_block;

    wire [4:0] w_ctrl_current_state;

    reg r_int_rst_dff, r_sleep_start_dff;
    always @(posedge w_int_rst, negedge w_iob_func_mode) begin
        if (!w_iob_func_mode) begin
            r_int_rst_dff <= 0;
        end
        else begin
            r_int_rst_dff <= 1;
        end
    end

    always @(posedge w_sleep_start, negedge w_iob_func_mode) begin
        if (!w_iob_func_mode) begin
            r_sleep_start_dff <= 0;
        end
        else begin
            r_sleep_start_dff <= 1;
        end
    end

    assign  w_nrst_soc   = w_nRST_iso_en ? 1'b1 : w_iob_func_mode && r_otp_reg[6][24] ? ~r_int_rst_dff     : w_nrst_din  ;
    assign  w_nsleep_soc =                        w_iob_func_mode && r_otp_reg[6][23] ? ~r_sleep_start_dff : w_nsleep_din;

    assign w_user_clk_ready   = w_pll_osc_init_ready_en ? (~w_iob_osc_en || w_osc_ready_block) && (~w_iob_pll_en || w_pll_lock_block || w_iob_bypass) : 1'b1;
    assign w_all_user_clk_low = (~w_osc_ready_user) && (~w_pll_rdy);

    assign w_force_dev_sleep_dis = r_otp_reg[6][25];
    assign w_gpio_keep = r_otp_reg[6][0];
    assign w_pll_osc_init_ready_en = r_otp_reg[6][18];

    ctrl #(
        .BG_FORCE_DLY_CNT       	(500   ),
        .LOAD_BITSTREAM_CNT     	(5000  ),
        .PRE_LOAD_BITSTREAM_CNT 	(1000  ),
        .LOAD_INIT_CNT          	(500   ))
    u_ctrl(
        .i_vdd_ok                     	(w_vdd_ok                       ),
        .i_por                         	(w_por                          ),
        .i_nRST                        	(w_nrst_soc                     ),
        .i_nSLEEP                      	(w_nsleep_soc                   ),
        .i_ctrl_clk                    	(w_ctrl_clk                     ),
        .i_ctrl_clk_rdy                	(w_osc_ready_block              ),
        .i_user_clk_ready              	(w_user_clk_ready               ),
        .i_all_user_clk_low            	(w_all_user_clk_low             ),
        .i_force_dev_sleep_dis         	(w_force_dev_sleep_dis          ),
        .i_gpio_keep                   	(w_gpio_keep                    ),
        .o_retention_cfg_reg_set       	(w_retention_cfg_reg_set        ),
        .o_retention_iob_set           	(w_retention_iob_set            ),
        .o_retention_cfg_reg_rst       	(w_retention_cfg_reg_rst        ),
        .o_retention_iob_rst           	(w_retention_iob_rst            ),
        .o_ctrl_gpio_fn_inp_gating     	(w_ctrl_gpio_fn_inp_gating      ),
        .o_ctrl_gpio_fn_out_gating     	(w_ctrl_gpio_fn_out_gating      ),
        .o_ctrl_gpio_fn_oe_gating      	(w_ctrl_gpio_fn_oe_gating       ),
        .o_ctrl_gpio_1x_pullup_en_reg  	(w_ctrl_gpio_1x_pullup_en_reg   ),
        .o_ctrl_gpio_2x_pullup_en_reg  	(w_ctrl_gpio_2x_pullup_en_reg   ),
        .o_ctrl_gpio_2x_buffer_en_reg  	(w_ctrl_gpio_2x_buffer_en_reg   ),
        .o_ctrl_gpio_open_drain_en_reg 	(w_ctrl_gpio_open_drain_en_reg  ),
        .o_nSLEEP_nRST_pullup_en       	(w_nSLEEP_nRST_pullup_en        ),
        .o_ctrl_clk_req                	(w_ctrl_clk_req                 ),
        .o_ctrl_current_state          	(w_ctrl_current_state           ),
        .o_pll_override              	(w_pll_override                 ),
        .o_iob_func_mode               	(w_iob_func_mode                ),
        .o_all_user_clk_rst            	(w_all_user_clk_rst             ),
        .o_nRST_iso_en            	    (w_nRST_iso_en                  ),
        .o_bram_sleep_en          	    (w_bram_sleep_en                ),
        .o_bram_rst_en            	    (w_bram_rst_en                  ),
        .o_config_done            	    (w_config_done                  )
    );

//----------------------------------------------------------------------------------//
//                                   OSC & PLL                                      //
//----------------------------------------------------------------------------------//
    wire w_iob_osc_clk           ;
    wire w_reg_osc_en_2ff_sync   ;
    wire w_en_user_clk_sync      ;
    wire w_pll_fout_raw          ;
    wire w_iob_pll_ref_clk_sel   ;
    wire w_ref_clk_ext           ;
    wire [5:0]  w_iob_refdiv     ;
    wire [11:0] w_iob_fbdiv      ;
    wire [2:0]  w_iob_posdiv1_out;
    wire [2:0]  w_iob_posdiv2_out;
    wire w_iob_bypass            ;
    wire w_pll_user_fout         ;
    wire w_pll_lock_block        ;       
    wire w_pll_soc_fout          ;                
    wire w_all_user_clk_nrst     ;

    assign w_all_user_clk_nrst   = ~w_all_user_clk_rst;
    assign w_ref_clk_ext         = w_digital_input_gpio_to_pad_ctrl [2] & w_all_user_clk_nrst;
    assign w_reg_osc_en_2ff_sync = r_otp_reg[6][22];
    assign w_en_user_clk_sync    = r_otp_reg[6][21];

    clk_ctrl u_clk_ctrl(
        .i_por_raw             	(w_por                  ),
        .i_osc_en_request      	(w_ctrl_clk_req         ),
        .i_iob_osc_en          	(w_iob_osc_en           ),
        .i_func_mode           	(w_iob_func_mode        ),
        .i_reg_osc_en_2ff_sync 	(w_reg_osc_en_2ff_sync  ), 
        .i_all_user_clk_nrst   	(w_all_user_clk_nrst    ),
        .i_pll_en_request      	(1'b0                   ), 
        .i_iob_pll_en          	(w_iob_pll_en           ),
        .i_pll_ref_clk_sel     	(w_iob_pll_ref_clk_sel  ),
        .i_ref_clk_ext         	(w_ref_clk_ext          ),
        .i_reg_refdiv          	(w_iob_refdiv           ), 
        .i_reg_fbdiv           	(w_iob_fbdiv            ), 
        .i_reg_posdiv1_out     	(w_iob_posdiv1_out      ), 
        .i_reg_posdiv2_out     	(w_iob_posdiv2_out      ), 
        .i_reg_bypass          	(w_iob_bypass           ), 
        .i_en_user_clk_sync    	(w_en_user_clk_sync     ),
        .i_pll_en_override      (w_pll_override         ), 

        .o_osc_ready_user       (w_osc_ready_user       ),
        .o_osc_ready_block      (w_osc_ready_block      ),
        .o_soc_osc_clk          (w_ctrl_clk             ),
        .o_user_osc_clk         (w_iob_osc_clk          ),
        
        .o_pll_lock             (w_pll_rdy              ),     
        .o_pll_lock_block       (w_pll_lock_block       ),
        .o_pll_soc_fout         (w_pll_soc_fout         ),
        .o_pll_user_fout        (w_pll_user_fout        ) 
    );
    
//----------------------------------------------------------------------------------//
//                                LOGIC AS CLOCK                                    //
//----------------------------------------------------------------------------------//

    wire w_ref_logic_as_clk0            ;
    wire w_ref_logic_as_clk1            ;
    wire w_logic_as_clk0_en             ;
    wire w_logic_as_clk1_en             ;
    wire w_reg_data_as_clk_en_2ff_sync_0;
    wire w_reg_data_as_clk_en_2ff_sync_1;

    wire w_logic_as_clk0                ;
    wire w_logic_as_clk1                ;
    wire w_data_as_clk_0_ready_soc      ;
    wire w_data_as_clk_1_ready_soc      ;

    assign w_reg_data_as_clk_en_2ff_sync_0 = r_otp_reg[6][20];
    assign w_reg_data_as_clk_en_2ff_sync_1 = r_otp_reg[6][19];

    logic_as_clock u_logic_as_clock0 (
        .i_all_user_clk_nrst           (w_all_user_clk_nrst            ),
        .i_func_mode                   (w_iob_func_mode                ),
        .i_iob_data_as_clk_en_user     (w_logic_as_clk0_en             ),
        .i_iob_data_as_clk_user        (w_ref_logic_as_clk0            ),
        .i_reg_data_as_clk_en_2ff_sync (w_reg_data_as_clk_en_2ff_sync_0),

        .o_data_as_clk_in_user         (w_logic_as_clk0                ),
        .o_data_as_clk_ready_soc       (w_data_as_clk_0_ready_soc      )
    );
    
    logic_as_clock u_logic_as_clock1 (
        .i_all_user_clk_nrst           (w_all_user_clk_nrst            ),
        .i_func_mode                   (w_iob_func_mode                ),
        .i_iob_data_as_clk_en_user     (w_logic_as_clk1_en             ),
        .i_iob_data_as_clk_user        (w_ref_logic_as_clk1            ),
        .i_reg_data_as_clk_en_2ff_sync (w_reg_data_as_clk_en_2ff_sync_1),

        .o_data_as_clk_in_user         (w_logic_as_clk1                ),
        .o_data_as_clk_ready_soc       (w_data_as_clk_1_ready_soc      )
    );

//----------------------------------------------------------------------------------//
//                                   FPGA_CORE                                      //
//----------------------------------------------------------------------------------//
    
    fpga_core_abc463c_test u_fpga_core_abc463c_test(
        .fpga_core_ready        	(w_config_done                          ), 
        .func_mode              	(w_iob_func_mode                        ),
        .nrst                   	(w_nrst_din                             ),
        .nsleep                 	(w_nsleep_din                           ),
        .int_fpga_sleep         	(w_sleep_start                          ),
        .int_fpga_reset         	(w_int_rst                              ),
        .ref_logic_as_clk0      	(w_ref_logic_as_clk0                    ),
        .ref_logic_as_clk1      	(w_ref_logic_as_clk1                    ),
        .logic_as_clk0_en       	(w_logic_as_clk0_en                     ),
        .logic_as_clk1_en       	(w_logic_as_clk1_en                     ),
        .bram0_rdata            	(w_bram0_rdata                          ),
        .bram0_wdata            	(w_bram0_wdata                          ),
        .bram0_raddr            	(w_bram0_raddr                          ),
        .bram0_waddr            	(w_bram0_waddr                          ),
        .bram0_wclkinv          	(w_bram0_wclkinv                        ),
        .bram0_rclkinv          	(w_bram0_rclkinv                        ),
        .bram0_ratio            	(w_bram0_ratio                          ),
        .bram0_nren             	(w_bram0_nren                           ),
        .bram0_nrclken          	(w_bram0_nrclken                        ),
        .bram0_nwen             	(w_bram0_nwen                           ),
        .bram0_nwclken          	(w_bram0_nwclken                        ),
        .bram1_rdata            	(w_bram1_rdata                          ),
        .bram1_wdata            	(w_bram1_wdata                          ),
        .bram1_raddr            	(w_bram1_raddr                          ),
        .bram1_waddr            	(w_bram1_waddr                          ),
        .bram1_wclkinv          	(w_bram1_wclkinv                        ),
        .bram1_rclkinv          	(w_bram1_rclkinv                        ),
        .bram1_ratio            	(w_bram1_ratio                          ),
        .bram1_nren             	(w_bram1_nren                           ),
        .bram1_nrclken          	(w_bram1_nrclken                        ),
        .bram1_nwen             	(w_bram1_nwen                           ),
        .bram1_nwclken          	(w_bram1_nwclken                        ),
        .bram2_rdata            	(w_bram2_rdata                          ),
        .bram2_wdata            	(w_bram2_wdata                          ),
        .bram2_raddr            	(w_bram2_raddr                          ),
        .bram2_waddr            	(w_bram2_waddr                          ),
        .bram2_wclkinv          	(w_bram2_wclkinv                        ),
        .bram2_rclkinv          	(w_bram2_rclkinv                        ),
        .bram2_ratio            	(w_bram2_ratio                          ),
        .bram2_nren             	(w_bram2_nren                           ),
        .bram2_nrclken          	(w_bram2_nrclken                        ),
        .bram2_nwen             	(w_bram2_nwen                           ),
        .bram2_nwclken          	(w_bram2_nwclken                        ),
        .bram3_rdata            	(w_bram3_rdata                          ),
        .bram3_wdata            	(w_bram3_wdata                          ),
        .bram3_raddr            	(w_bram3_raddr                          ),
        .bram3_waddr            	(w_bram3_waddr                          ),
        .bram3_wclkinv          	(w_bram3_wclkinv                        ),
        .bram3_rclkinv          	(w_bram3_rclkinv                        ),
        .bram3_ratio            	(w_bram3_ratio                          ),
        .bram3_nren             	(w_bram3_nren                           ),
        .bram3_nrclken          	(w_bram3_nrclken                        ),
        .bram3_nwen             	(w_bram3_nwen                           ),
        .bram3_nwclken          	(w_bram3_nwclken                        ),
        .bram4_rdata            	(w_bram4_rdata                          ),
        .bram4_wdata            	(w_bram4_wdata                          ),
        .bram4_raddr            	(w_bram4_raddr                          ),
        .bram4_waddr            	(w_bram4_waddr                          ),
        .bram4_wclkinv          	(w_bram4_wclkinv                        ),
        .bram4_rclkinv          	(w_bram4_rclkinv                        ),
        .bram4_ratio            	(w_bram4_ratio                          ),
        .bram4_nren             	(w_bram4_nren                           ),
        .bram4_nrclken          	(w_bram4_nrclken                        ),
        .bram4_nwen             	(w_bram4_nwen                           ),
        .bram4_nwclken          	(w_bram4_nwclken                        ),
        .bram5_rdata            	(w_bram5_rdata                          ),
        .bram5_wdata            	(w_bram5_wdata                          ),
        .bram5_raddr            	(w_bram5_raddr                          ),
        .bram5_waddr            	(w_bram5_waddr                          ),
        .bram5_wclkinv          	(w_bram5_wclkinv                        ),
        .bram5_rclkinv          	(w_bram5_rclkinv                        ),
        .bram5_ratio            	(w_bram5_ratio                          ),
        .bram5_nren             	(w_bram5_nren                           ),
        .bram5_nrclken          	(w_bram5_nrclken                        ),
        .bram5_nwen             	(w_bram5_nwen                           ),
        .bram5_nwclken          	(w_bram5_nwclken                        ),
        .bram6_rdata            	(w_bram6_rdata                          ),
        .bram6_wdata            	(w_bram6_wdata                          ),
        .bram6_raddr            	(w_bram6_raddr                          ),
        .bram6_waddr            	(w_bram6_waddr                          ),
        .bram6_wclkinv          	(w_bram6_wclkinv                        ),
        .bram6_rclkinv          	(w_bram6_rclkinv                        ),
        .bram6_ratio            	(w_bram6_ratio                          ),
        .bram6_nren             	(w_bram6_nren                           ),
        .bram6_nrclken          	(w_bram6_nrclken                        ),
        .bram6_nwen             	(w_bram6_nwen                           ),
        .bram6_nwclken          	(w_bram6_nwclken                        ),
        .bram7_rdata            	(w_bram7_rdata                          ),
        .bram7_wdata            	(w_bram7_wdata                          ),
        .bram7_raddr            	(w_bram7_raddr                          ),
        .bram7_waddr            	(w_bram7_waddr                          ),
        .bram7_wclkinv          	(w_bram7_wclkinv                        ),
        .bram7_rclkinv          	(w_bram7_rclkinv                        ),
        .bram7_ratio            	(w_bram7_ratio                          ),
        .bram7_nren             	(w_bram7_nren                           ),
        .bram7_nrclken          	(w_bram7_nrclken                        ),
        .bram7_nwen             	(w_bram7_nwen                           ),
        .bram7_nwclken          	(w_bram7_nwclken                        ),
        .logic_as_clk0          	(w_logic_as_clk0                        ),
        .logic_as_clk1          	(w_logic_as_clk1                        ),
        .osc_clk                	(w_iob_osc_clk                          ),
        .pll_clk                	(w_pll_user_fout                        ),
        .ref_bram_0_3_read_clk  	(w_ref_bram_0_3_read_clk                ), 
        .ref_bram_0_3_write_clk 	(w_ref_bram_0_3_write_clk               ), 
        .ref_bram_4_7_read_clk  	(w_ref_bram_4_7_read_clk                ), 
        .ref_bram_4_7_write_clk 	(w_ref_bram_4_7_write_clk               ), 
        .gpio_in                	(w_gpio_digital_in_pad_ctrl_to_iob_dly  ),
        .gpio_oe                	(w_iob_output_enable_to_pad_ctrl        ),
        .gpio_out               	(w_iob_digital_out_to_pad_ctrl          ),
        .osc_ready              	(w_osc_ready_user                       ),
        .osc_en                 	(w_iob_osc_en                           ),
        .pll_lock               	(w_pll_rdy                              ),
        .pll_ref_clk_sel        	(w_iob_pll_ref_clk_sel                  ),
        .pll_bypass             	(w_iob_bypass                           ),
        .pll_en                 	(w_iob_pll_en                           ),
        .pll_fbdiv              	(w_iob_fbdiv                            ),
        .pll_postdiv1           	(w_iob_posdiv1_out                      ),
        .pll_postdiv2           	(w_iob_posdiv2_out                      ),
        .pll_refdiv             	(w_iob_refdiv                           )
    );

//----------------------------------------------------------------------------------//
//                  GPIO PATH DLY : PAD_CTRL TO FPGA CORE                           //
//----------------------------------------------------------------------------------//
    wire [18:0] w_gpio_digital_in_pad_ctrl_to_iob_dly;
    assign #(1.25, 1.03) w_gpio_digital_in_pad_ctrl_to_iob_dly[0]  = w_gpio_digital_in_pad_ctrl_to_iob[0] ;
    assign #(1.22, 0.99) w_gpio_digital_in_pad_ctrl_to_iob_dly[1]  = w_gpio_digital_in_pad_ctrl_to_iob[1] ;
    assign #(2.15, 1.82) w_gpio_digital_in_pad_ctrl_to_iob_dly[2]  = w_gpio_digital_in_pad_ctrl_to_iob[2] ;
    assign #(1.56, 1.34) w_gpio_digital_in_pad_ctrl_to_iob_dly[3]  = w_gpio_digital_in_pad_ctrl_to_iob[3] ;
    assign #(2.17, 1.90) w_gpio_digital_in_pad_ctrl_to_iob_dly[4]  = w_gpio_digital_in_pad_ctrl_to_iob[4] ;
    assign #(2.04, 1.76) w_gpio_digital_in_pad_ctrl_to_iob_dly[5]  = w_gpio_digital_in_pad_ctrl_to_iob[5] ;
    assign #(1.81, 1.60) w_gpio_digital_in_pad_ctrl_to_iob_dly[6]  = w_gpio_digital_in_pad_ctrl_to_iob[6] ;
    assign #(2.20, 1.96) w_gpio_digital_in_pad_ctrl_to_iob_dly[7]  = w_gpio_digital_in_pad_ctrl_to_iob[7] ;
    assign #(3.85, 3.62) w_gpio_digital_in_pad_ctrl_to_iob_dly[8]  = w_gpio_digital_in_pad_ctrl_to_iob[8] ;
    assign #(3.70, 3.50) w_gpio_digital_in_pad_ctrl_to_iob_dly[9]  = w_gpio_digital_in_pad_ctrl_to_iob[9] ;
    assign #(3.39, 3.22) w_gpio_digital_in_pad_ctrl_to_iob_dly[10] = w_gpio_digital_in_pad_ctrl_to_iob[10];
    assign #(3.63, 3.40) w_gpio_digital_in_pad_ctrl_to_iob_dly[11] = w_gpio_digital_in_pad_ctrl_to_iob[11];
    assign #(3.82, 3.57) w_gpio_digital_in_pad_ctrl_to_iob_dly[12] = w_gpio_digital_in_pad_ctrl_to_iob[12];
    assign #(1.17, 0.97) w_gpio_digital_in_pad_ctrl_to_iob_dly[13] = w_gpio_digital_in_pad_ctrl_to_iob[13];
    assign #(1.13, 0.91) w_gpio_digital_in_pad_ctrl_to_iob_dly[14] = w_gpio_digital_in_pad_ctrl_to_iob[14];
    assign #(1.14, 0.90) w_gpio_digital_in_pad_ctrl_to_iob_dly[15] = w_gpio_digital_in_pad_ctrl_to_iob[15];
    assign #(2.56, 2.30) w_gpio_digital_in_pad_ctrl_to_iob_dly[16] = w_gpio_digital_in_pad_ctrl_to_iob[16];  
    assign #(2.60, 2.33) w_gpio_digital_in_pad_ctrl_to_iob_dly[17] = w_gpio_digital_in_pad_ctrl_to_iob[17];  
    assign #(2.76, 2.52) w_gpio_digital_in_pad_ctrl_to_iob_dly[18] = w_gpio_digital_in_pad_ctrl_to_iob[18];  

//----------------------------------------------------------------------------------//
//                      GPIO PATH DLY : GPIO_PAD TO PAD_CTRL                        //
//----------------------------------------------------------------------------------//
    wire [18:0] w_digital_input_gpio_to_pad_ctrl_dly;
    assign w_digital_input_gpio_to_pad_ctrl_dly[0]  = w_digital_input_gpio_to_pad_ctrl[0] ;
    assign w_digital_input_gpio_to_pad_ctrl_dly[1]  = w_digital_input_gpio_to_pad_ctrl[1] ;
    assign w_digital_input_gpio_to_pad_ctrl_dly[2]  = w_digital_input_gpio_to_pad_ctrl[2] ;
    assign w_digital_input_gpio_to_pad_ctrl_dly[3]  = w_digital_input_gpio_to_pad_ctrl[3] ;
    assign w_digital_input_gpio_to_pad_ctrl_dly[4]  = w_digital_input_gpio_to_pad_ctrl[4] ;
    assign w_digital_input_gpio_to_pad_ctrl_dly[5]  = w_digital_input_gpio_to_pad_ctrl[5] ;
    assign w_digital_input_gpio_to_pad_ctrl_dly[6]  = w_digital_input_gpio_to_pad_ctrl[6] ;
    assign w_digital_input_gpio_to_pad_ctrl_dly[7]  = w_digital_input_gpio_to_pad_ctrl[7] ;
    assign w_digital_input_gpio_to_pad_ctrl_dly[8]  = w_digital_input_gpio_to_pad_ctrl[8] ;
    assign w_digital_input_gpio_to_pad_ctrl_dly[9]  = w_digital_input_gpio_to_pad_ctrl[9] ;
    assign w_digital_input_gpio_to_pad_ctrl_dly[10] = w_digital_input_gpio_to_pad_ctrl[10];
    assign w_digital_input_gpio_to_pad_ctrl_dly[11] = w_digital_input_gpio_to_pad_ctrl[11];
    assign w_digital_input_gpio_to_pad_ctrl_dly[12] = w_digital_input_gpio_to_pad_ctrl[12];
    assign w_digital_input_gpio_to_pad_ctrl_dly[13] = w_digital_input_gpio_to_pad_ctrl[13];
    assign w_digital_input_gpio_to_pad_ctrl_dly[14] = w_digital_input_gpio_to_pad_ctrl[14];
    assign w_digital_input_gpio_to_pad_ctrl_dly[15] = w_digital_input_gpio_to_pad_ctrl[15];
    assign w_digital_input_gpio_to_pad_ctrl_dly[16] = w_digital_input_gpio_to_pad_ctrl[16]; 
    assign w_digital_input_gpio_to_pad_ctrl_dly[17] = w_digital_input_gpio_to_pad_ctrl[17]; 
    assign w_digital_input_gpio_to_pad_ctrl_dly[18] = w_digital_input_gpio_to_pad_ctrl[18]; 

//----------------------------------------------------------------------------------//
//                      GPIO PATH DLY : CORE TO PAD_CTRL                            //
//----------------------------------------------------------------------------------//
    wire [18:0] w_iob_output_enable_to_pad_ctrl_dly, w_iob_digital_out_to_pad_ctrl_dly;
    
    assign w_iob_output_enable_to_pad_ctrl_dly[0]  = w_iob_output_enable_to_pad_ctrl[0] ;   
    assign w_iob_output_enable_to_pad_ctrl_dly[1]  = w_iob_output_enable_to_pad_ctrl[1] ;   
    assign w_iob_output_enable_to_pad_ctrl_dly[2]  = w_iob_output_enable_to_pad_ctrl[2] ;   
    assign w_iob_output_enable_to_pad_ctrl_dly[3]  = w_iob_output_enable_to_pad_ctrl[3] ;   
    assign w_iob_output_enable_to_pad_ctrl_dly[4]  = w_iob_output_enable_to_pad_ctrl[4] ;   
    assign w_iob_output_enable_to_pad_ctrl_dly[5]  = w_iob_output_enable_to_pad_ctrl[5] ;   
    assign w_iob_output_enable_to_pad_ctrl_dly[6]  = w_iob_output_enable_to_pad_ctrl[6] ;   
    assign w_iob_output_enable_to_pad_ctrl_dly[7]  = w_iob_output_enable_to_pad_ctrl[7] ;   
    assign w_iob_output_enable_to_pad_ctrl_dly[8]  = w_iob_output_enable_to_pad_ctrl[8] ;   
    assign w_iob_output_enable_to_pad_ctrl_dly[9]  = w_iob_output_enable_to_pad_ctrl[9] ;   
    assign w_iob_output_enable_to_pad_ctrl_dly[10] = w_iob_output_enable_to_pad_ctrl[10];   
    assign w_iob_output_enable_to_pad_ctrl_dly[11] = w_iob_output_enable_to_pad_ctrl[11];   
    assign w_iob_output_enable_to_pad_ctrl_dly[12] = w_iob_output_enable_to_pad_ctrl[12];   
    assign w_iob_output_enable_to_pad_ctrl_dly[13] = w_iob_output_enable_to_pad_ctrl[13];   
    assign w_iob_output_enable_to_pad_ctrl_dly[14] = w_iob_output_enable_to_pad_ctrl[14];   
    assign w_iob_output_enable_to_pad_ctrl_dly[15] = w_iob_output_enable_to_pad_ctrl[15];   
    assign w_iob_output_enable_to_pad_ctrl_dly[16] = w_iob_output_enable_to_pad_ctrl[16];   
    assign w_iob_output_enable_to_pad_ctrl_dly[17] = w_iob_output_enable_to_pad_ctrl[17];   
    assign w_iob_output_enable_to_pad_ctrl_dly[18] = w_iob_output_enable_to_pad_ctrl[18];   

    assign w_iob_digital_out_to_pad_ctrl_dly[0]  = w_iob_digital_out_to_pad_ctrl[0] ;  
    assign w_iob_digital_out_to_pad_ctrl_dly[1]  = w_iob_digital_out_to_pad_ctrl[1] ;  
    assign w_iob_digital_out_to_pad_ctrl_dly[2]  = w_iob_digital_out_to_pad_ctrl[2] ;  
    assign w_iob_digital_out_to_pad_ctrl_dly[3]  = w_iob_digital_out_to_pad_ctrl[3] ;
    assign w_iob_digital_out_to_pad_ctrl_dly[4]  = w_iob_digital_out_to_pad_ctrl[4] ;  
    assign w_iob_digital_out_to_pad_ctrl_dly[5]  = w_iob_digital_out_to_pad_ctrl[5] ;
    assign w_iob_digital_out_to_pad_ctrl_dly[6]  = w_iob_digital_out_to_pad_ctrl[6] ;
    assign w_iob_digital_out_to_pad_ctrl_dly[7]  = w_iob_digital_out_to_pad_ctrl[7] ;
    assign w_iob_digital_out_to_pad_ctrl_dly[8]  = w_iob_digital_out_to_pad_ctrl[8] ;
    assign w_iob_digital_out_to_pad_ctrl_dly[9]  = w_iob_digital_out_to_pad_ctrl[9] ;
    assign w_iob_digital_out_to_pad_ctrl_dly[10] = w_iob_digital_out_to_pad_ctrl[10];
    assign w_iob_digital_out_to_pad_ctrl_dly[11] = w_iob_digital_out_to_pad_ctrl[11];
    assign w_iob_digital_out_to_pad_ctrl_dly[12] = w_iob_digital_out_to_pad_ctrl[12];
    assign w_iob_digital_out_to_pad_ctrl_dly[13] = w_iob_digital_out_to_pad_ctrl[13];
    assign w_iob_digital_out_to_pad_ctrl_dly[14] = w_iob_digital_out_to_pad_ctrl[14];
    assign w_iob_digital_out_to_pad_ctrl_dly[15] = w_iob_digital_out_to_pad_ctrl[15];
    assign w_iob_digital_out_to_pad_ctrl_dly[16] = w_iob_digital_out_to_pad_ctrl[16];  
    assign w_iob_digital_out_to_pad_ctrl_dly[17] = w_iob_digital_out_to_pad_ctrl[17];  
    assign w_iob_digital_out_to_pad_ctrl_dly[18] = w_iob_digital_out_to_pad_ctrl[18];  

//----------------------------------------------------------------------------------//
//                      GPIO PATH DLY : PAD_CTRL TO GPIO_PAD                        //
//----------------------------------------------------------------------------------//
    wire [18:0] w_digital_out_en_pad_ctrl_to_gpio_dly, w_digital_output_pad_ctrl_to_gpio_dly;

    assign #(1.58, 1.45) w_digital_out_en_pad_ctrl_to_gpio_dly[0]  = w_digital_out_en_pad_ctrl_to_gpio[0] ;
    assign #(1.37, 1.23) w_digital_out_en_pad_ctrl_to_gpio_dly[1]  = w_digital_out_en_pad_ctrl_to_gpio[1] ;
    assign #(1.46, 1.37) w_digital_out_en_pad_ctrl_to_gpio_dly[2]  = w_digital_out_en_pad_ctrl_to_gpio[2] ;
    assign #(1.73, 1.66) w_digital_out_en_pad_ctrl_to_gpio_dly[3]  = w_digital_out_en_pad_ctrl_to_gpio[3] ;
    assign #(1.55, 1.54) w_digital_out_en_pad_ctrl_to_gpio_dly[4]  = w_digital_out_en_pad_ctrl_to_gpio[4] ;
    assign #(1.50, 1.48) w_digital_out_en_pad_ctrl_to_gpio_dly[5]  = w_digital_out_en_pad_ctrl_to_gpio[5] ;
    assign #(1.63, 1.52) w_digital_out_en_pad_ctrl_to_gpio_dly[6]  = w_digital_out_en_pad_ctrl_to_gpio[6] ;
    assign #(2.57, 2.43) w_digital_out_en_pad_ctrl_to_gpio_dly[7]  = w_digital_out_en_pad_ctrl_to_gpio[7] ;
    assign #(4.03, 3.99) w_digital_out_en_pad_ctrl_to_gpio_dly[8]  = w_digital_out_en_pad_ctrl_to_gpio[8] ;
    assign #(3.39, 3.42) w_digital_out_en_pad_ctrl_to_gpio_dly[9]  = w_digital_out_en_pad_ctrl_to_gpio[9] ;
    assign #(4.46, 4.30) w_digital_out_en_pad_ctrl_to_gpio_dly[10] = w_digital_out_en_pad_ctrl_to_gpio[10];
    assign #(4.35, 4.03) w_digital_out_en_pad_ctrl_to_gpio_dly[11] = w_digital_out_en_pad_ctrl_to_gpio[11];
    assign #(5.02, 4.79) w_digital_out_en_pad_ctrl_to_gpio_dly[12] = w_digital_out_en_pad_ctrl_to_gpio[12];
    assign #(4.09, 3.97) w_digital_out_en_pad_ctrl_to_gpio_dly[13] = w_digital_out_en_pad_ctrl_to_gpio[13];
    assign #(2.25, 2.14) w_digital_out_en_pad_ctrl_to_gpio_dly[14] = w_digital_out_en_pad_ctrl_to_gpio[14];
    assign #(3.69, 3.57) w_digital_out_en_pad_ctrl_to_gpio_dly[15] = w_digital_out_en_pad_ctrl_to_gpio[15];
    assign #(3.19, 2.85) w_digital_out_en_pad_ctrl_to_gpio_dly[16] = w_digital_out_en_pad_ctrl_to_gpio[16];
    assign #(2.92, 2.71) w_digital_out_en_pad_ctrl_to_gpio_dly[17] = w_digital_out_en_pad_ctrl_to_gpio[17];
    assign #(3.46, 3.26) w_digital_out_en_pad_ctrl_to_gpio_dly[18] = w_digital_out_en_pad_ctrl_to_gpio[18];

    assign #(4.83, 4.72) w_digital_output_pad_ctrl_to_gpio_dly[0]  = w_digital_output_pad_ctrl_to_gpio[0] ;  
    assign #(4.43, 4.34) w_digital_output_pad_ctrl_to_gpio_dly[1]  = w_digital_output_pad_ctrl_to_gpio[1] ;  
    assign #(4.83, 4.79) w_digital_output_pad_ctrl_to_gpio_dly[2]  = w_digital_output_pad_ctrl_to_gpio[2] ;  
    assign #(4.67, 4.57) w_digital_output_pad_ctrl_to_gpio_dly[3]  = w_digital_output_pad_ctrl_to_gpio[3] ;
    assign #(3.77, 3.80) w_digital_output_pad_ctrl_to_gpio_dly[4]  = w_digital_output_pad_ctrl_to_gpio[4] ;  
    assign #(4.59, 4.50) w_digital_output_pad_ctrl_to_gpio_dly[5]  = w_digital_output_pad_ctrl_to_gpio[5] ;
    assign #(4.49, 4.40) w_digital_output_pad_ctrl_to_gpio_dly[6]  = w_digital_output_pad_ctrl_to_gpio[6] ;
    assign #(4.78, 4.73) w_digital_output_pad_ctrl_to_gpio_dly[7]  = w_digital_output_pad_ctrl_to_gpio[7] ;
    assign #(5.85, 5.73) w_digital_output_pad_ctrl_to_gpio_dly[8]  = w_digital_output_pad_ctrl_to_gpio[8] ;
    assign #(5.71, 5.65) w_digital_output_pad_ctrl_to_gpio_dly[9]  = w_digital_output_pad_ctrl_to_gpio[9] ;
    assign #(5.88, 5.85) w_digital_output_pad_ctrl_to_gpio_dly[10] = w_digital_output_pad_ctrl_to_gpio[10];
    assign #(7.32, 7.16) w_digital_output_pad_ctrl_to_gpio_dly[11] = w_digital_output_pad_ctrl_to_gpio[11];
    assign #(6.95, 6.82) w_digital_output_pad_ctrl_to_gpio_dly[12] = w_digital_output_pad_ctrl_to_gpio[12];
    assign #(6.11, 6.11) w_digital_output_pad_ctrl_to_gpio_dly[13] = w_digital_output_pad_ctrl_to_gpio[13];
    assign #(6.29, 6.25) w_digital_output_pad_ctrl_to_gpio_dly[14] = w_digital_output_pad_ctrl_to_gpio[14];
    assign #(5.08, 5.10) w_digital_output_pad_ctrl_to_gpio_dly[15] = w_digital_output_pad_ctrl_to_gpio[15];
    assign #(5.37, 5.27) w_digital_output_pad_ctrl_to_gpio_dly[16] = w_digital_output_pad_ctrl_to_gpio[16];  
    assign #(5.54, 5.49) w_digital_output_pad_ctrl_to_gpio_dly[17] = w_digital_output_pad_ctrl_to_gpio[17];  
    assign #(5.73, 5.66) w_digital_output_pad_ctrl_to_gpio_dly[18] = w_digital_output_pad_ctrl_to_gpio[18];  

///////////////////////////////////////////////////////////////////////////
///                         BRAM                                         //
///////////////////////////////////////////////////////////////////////////
    wire       w_bram_north_pg_reg_val;
    wire       w_bram_south_pg_reg_val;
    wire       w_bram_keep_reg_val;
    wire [7:0] w_bram0_rdata;
    wire [7:0] w_bram1_rdata;
    wire [7:0] w_bram2_rdata;
    wire [7:0] w_bram3_rdata;
    wire [7:0] w_bram4_rdata;
    wire [7:0] w_bram5_rdata;
    wire [7:0] w_bram6_rdata;
    wire [7:0] w_bram7_rdata;
    wire [7:0] w_bram0_wdata;
    wire [7:0] w_bram1_wdata;
    wire [7:0] w_bram2_wdata;
    wire [7:0] w_bram3_wdata;
    wire [7:0] w_bram4_wdata;
    wire [7:0] w_bram5_wdata;
    wire [7:0] w_bram6_wdata;
    wire [7:0] w_bram7_wdata;

    wire [8:0] w_bram0_raddr;
    wire [8:0] w_bram1_raddr;
    wire [8:0] w_bram2_raddr;
    wire [8:0] w_bram3_raddr;
    wire [8:0] w_bram4_raddr;
    wire [8:0] w_bram5_raddr;
    wire [8:0] w_bram6_raddr;
    wire [8:0] w_bram7_raddr;

    wire [8:0] w_bram0_waddr;
    wire [8:0] w_bram1_waddr;
    wire [8:0] w_bram2_waddr;
    wire [8:0] w_bram3_waddr;
    wire [8:0] w_bram4_waddr;
    wire [8:0] w_bram5_waddr;
    wire [8:0] w_bram6_waddr;
    wire [8:0] w_bram7_waddr;

    wire [1:0] w_bram0_ratio;
    wire [1:0] w_bram1_ratio;
    wire [1:0] w_bram2_ratio;
    wire [1:0] w_bram3_ratio;
    wire [1:0] w_bram4_ratio;
    wire [1:0] w_bram5_ratio;
    wire [1:0] w_bram6_ratio;
    wire [1:0] w_bram7_ratio;

    wire w_bram0_wclkinv;
    wire w_bram0_rclkinv;
    wire w_bram0_nren;
    wire w_bram0_nrclken;
    wire w_bram0_nwen;
    wire w_bram0_nwclken;

    wire w_bram1_wclkinv;
    wire w_bram1_rclkinv;
    wire w_bram1_nren;
    wire w_bram1_nrclken;
    wire w_bram1_nwen;
    wire w_bram1_nwclken;

    wire w_bram2_wclkinv;
    wire w_bram2_rclkinv;
    wire w_bram2_nren;
    wire w_bram2_nrclken;
    wire w_bram2_nwen;
    wire w_bram2_nwclken;

    wire w_bram3_wclkinv;
    wire w_bram3_rclkinv;
    wire w_bram3_nren;
    wire w_bram3_nrclken;
    wire w_bram3_nwen;
    wire w_bram3_nwclken;

    wire w_bram4_wclkinv;
    wire w_bram4_rclkinv;
    wire w_bram4_nren;
    wire w_bram4_nrclken;
    wire w_bram4_nwen;
    wire w_bram4_nwclken;

    wire w_bram5_wclkinv;
    wire w_bram5_rclkinv;
    wire w_bram5_nren;
    wire w_bram5_nrclken;
    wire w_bram5_nwen;
    wire w_bram5_nwclken;

    wire w_bram6_wclkinv;
    wire w_bram6_rclkinv;
    wire w_bram6_nren;
    wire w_bram6_nrclken;
    wire w_bram6_nwen;
    wire w_bram6_nwclken;

    wire w_bram7_wclkinv;
    wire w_bram7_rclkinv;
    wire w_bram7_nren;
    wire w_bram7_nrclken;
    wire w_bram7_nwen;
    wire w_bram7_nwclken;

    wire w_ref_bram_0_3_write_clk;
    wire w_ref_bram_0_3_read_clk;
    wire w_ref_bram_4_7_write_clk;
    wire w_ref_bram_4_7_read_clk;

    assign w_bram_north_pg_reg_val = r_otp_reg[10][0];
    assign w_bram_south_pg_reg_val = r_otp_reg[10][1];
    assign w_bram_keep_reg_val = r_otp_reg[6][1];

    dual_port_hbram u_bram(

        .i_vdd_to_bram_0            (w_por),   
        .i_bram_north_write_clk     (w_ref_bram_0_3_write_clk),  
        .i_bram_north_read_clk      (w_ref_bram_0_3_read_clk),   
         
        .i_bram0_web_0              (w_bram0_nwen),        
        .i_bram0_1_wclken_0         ({w_bram1_nwclken, w_bram0_nwclken}),        
        .i_bram0_1_wclk_inv_0       ({w_bram1_wclkinv, w_bram0_wclkinv}),      
        .i_bram0_write_addr_0       (w_bram0_waddr),    
        .i_bram1_write_addr_0       (w_bram1_waddr),    
        .i_bram0_data_in_0          (w_bram0_wdata),         
        .i_bram1_web_0              (w_bram1_nwen),                              
        .i_bram1_data_in_0          (w_bram1_wdata),         

        .i_bram2_web_0              (w_bram2_nwen),        
        .i_bram2_3_wclken_0         ({w_bram3_nwclken, w_bram2_nwclken}),   
        .i_bram2_3_wclk_inv_0       ({w_bram3_wclkinv, w_bram2_wclkinv}),   
        .i_bram2_write_addr_0       (w_bram2_waddr),    
        .i_bram3_write_addr_0       (w_bram3_waddr),    
        .i_bram2_data_in_0          (w_bram2_wdata),         
        .i_bram3_web_0              (w_bram3_nwen),                          
        .i_bram3_data_in_0          (w_bram3_wdata),         

        .i_bram0_1_reb_0            ({w_bram1_nren, w_bram0_nren}),          
        .i_bram0_1_rclken_0         ({w_bram1_nrclken, w_bram0_nrclken}),        
        .i_bram0_1_rclk_inv_0       ({w_bram1_rclkinv, w_bram0_rclkinv}),      
        .i_bram0_read_addr_0        (w_bram0_raddr),         
        .i_bram1_read_addr_0        (w_bram1_raddr),                               

        .i_bram2_3_reb_0            ({w_bram3_nren, w_bram2_nren}),                
        .i_bram2_3_rclken_0         ({w_bram3_nrclken, w_bram2_nrclken}),    
        .i_bram2_3_rclk_inv_0       ({w_bram3_rclkinv, w_bram2_rclkinv}),    
        .i_bram2_read_addr_0        (w_bram2_raddr),         
        .i_bram3_read_addr_0        (w_bram3_raddr),                             

        .i_bram0_ratio_0            (w_bram0_ratio),  
        .i_bram1_ratio_0            (w_bram1_ratio),          
        .i_bram0_1_pd_0             ({2{w_bram_north_pg_reg_val}}),                          
        .i_bram2_ratio_0            (w_bram2_ratio),                            
        .i_bram3_ratio_0            (w_bram3_ratio),       
        .i_bram2_3_pd_0             ({2{w_bram_north_pg_reg_val}}),                     

        .o_bram0_data_out_0         (w_bram0_rdata),       
        .o_bram1_data_out_0         (w_bram1_rdata),        
        .o_bram2_data_out_0         (w_bram2_rdata),        
        .o_bram3_data_out_0         (w_bram3_rdata),    


        .i_vdd_to_bram_1            (w_por),                       
        .i_bram_south_write_clk     (w_ref_bram_4_7_write_clk),   
        .i_bram_south_read_clk      (w_ref_bram_4_7_read_clk),    
   
        .i_bram0_web_1              (w_bram4_nwen),        
        .i_bram0_1_wclken_1         ({w_bram5_nwclken, w_bram4_nwclken}),        
        .i_bram0_1_wclk_inv_1       ({w_bram5_wclkinv, w_bram4_wclkinv}),      
        .i_bram0_write_addr_1       (w_bram4_waddr), 
        .i_bram1_write_addr_1       (w_bram5_waddr), 
        .i_bram0_data_in_1          (w_bram4_wdata),         
        .i_bram1_web_1              (w_bram5_nwen),                                           
        .i_bram1_data_in_1          (w_bram5_wdata),         
   
        .i_bram2_web_1              (w_bram6_nwen),        
        .i_bram2_3_wclken_1         ({w_bram7_nwclken, w_bram6_nwclken}),   
        .i_bram2_3_wclk_inv_1       ({w_bram7_wclkinv, w_bram6_wclkinv}),   
        .i_bram2_write_addr_1       (w_bram6_waddr), 
        .i_bram3_write_addr_1       (w_bram7_waddr), 
        .i_bram2_data_in_1          (w_bram6_wdata),         
        .i_bram3_web_1              (w_bram7_nwen),                                     
        .i_bram3_data_in_1          (w_bram7_wdata),         
    
        .i_bram0_1_reb_1            ({w_bram5_nren, w_bram4_nren}),          
        .i_bram0_1_rclken_1         ({w_bram5_nrclken, w_bram4_nrclken}),        
        .i_bram0_1_rclk_inv_1       ({w_bram5_rclkinv, w_bram4_rclkinv}),      
        .i_bram0_read_addr_1        (w_bram4_raddr),
        .i_bram1_read_addr_1        (w_bram5_raddr),           
    
        .i_bram2_3_reb_1            ({w_bram7_nren, w_bram6_nren}),                
        .i_bram2_3_rclken_1         ({w_bram7_nrclken, w_bram6_nrclken}),    
        .i_bram2_3_rclk_inv_1       ({w_bram7_rclkinv, w_bram6_rclkinv}),    
        .i_bram2_read_addr_1        (w_bram6_raddr),
        .i_bram3_read_addr_1        (w_bram7_raddr),       
    
        .i_bram0_ratio_1            (w_bram4_ratio), 
        .i_bram1_ratio_1            (w_bram5_ratio),         
        .i_bram0_1_pd_1             ({2{w_bram_south_pg_reg_val}}),                                         
        .i_bram2_ratio_1            (w_bram6_ratio),                                            
        .i_bram3_ratio_1            (w_bram7_ratio),        
        .i_bram2_3_pd_1             ({2{w_bram_south_pg_reg_val}}),                               
   
        .o_bram0_data_out_1         (w_bram4_rdata),       
        .o_bram1_data_out_1         (w_bram5_rdata),        
        .o_bram2_data_out_1         (w_bram6_rdata),        
        .o_bram3_data_out_1         (w_bram7_rdata),    

        .i_reset_mode               (w_bram_rst_en),
        .i_bram_keep_reg            (w_bram_keep_reg_val),            
        .i_pwr_enable_reg           (2'b11),    
        .i_config_data              ({32768{1'b0}}), 
        .i_sleep_mode               (w_bram_sleep_en), 
        .i_config_done              (w_config_done) 
    );

endmodule
